update to Failure to Invalidate Session on Logout
bugcrowd/templates pull request #103
Opened 2022-04-28 04:31 UTC by RRudder

2022-04-28 06:14 UTC, vortexau requested changes

2022-04-28 06:14 UTC, vortexau commented on submissions/description/broken_authentication_and_session_management/failure_to_invalidate_session/on_logout/template.md
> +{{screenshot}}
Delete one of these screenshot entries

2022-05-10 23:51 UTC, RRudder commented
replaced by PR #137 due to conflicts

2022-05-10 23:51 UTC, closed without merging

2026-10-16 19:05 UTC, stonersdash26 approved these changes