Basic Subdomain takeover finding uplift
bugcrowd/templates pull request #108
Opened 2022-04-29 03:02 UTC by RRudder

2022-04-29 04:06 UTC, vortexau requested changes

2022-04-29 04:22 UTC, RRudder commented on submissions/description/server_security_misconfiguration/misconfigured_dns/basic_subdomain_takeover/template.md
> +```text
@vortexau please see latest commit addressing these changes

2022-05-04 07:10 UTC, evildaemond requested changes
1 comment then LGTM

2022-05-04 07:10 UTC, evildaemond commented on submissions/description/server_security_misconfiguration/misconfigured_dns/basic_subdomain_takeover/template.md
>  1. Register DNS record using a registration service and point to the following endpoint: {{URL}}
Quick change to remove this as this is not required for repro

2022-05-04 07:10 UTC, evildaemond commented on submissions/description/server_security_misconfiguration/misconfigured_dns/basic_subdomain_takeover/template.md
> +```text
Fixed in latest version

2022-05-04 07:13 UTC, evildaemond commented on submissions/description/server_security_misconfiguration/misconfigured_dns/basic_subdomain_takeover/template.md
>  1. Register DNS record using a registration service and point to the following endpoint: {{URL}}
Fixed

2022-05-04 07:13 UTC, evildaemond approved these changes

2022-05-04 07:13 UTC, merged