Base XSS Finding update
bugcrowd/templates pull request #130
Opened 2022-05-10 06:18 UTC by RRudder

2022-05-10 06:19 UTC, RRudder commented
Attempted to keep this generic enough that someone can pick it up and run with it

2022-05-11 06:24 UTC, evildaemond requested changes
1 update then LGTM

2022-05-11 06:24 UTC, evildaemond commented on submissions/description/cross_site_scripting_xss/template.md
> +Cross-Site Scripting (XSS) is a type of injection attack where malicious JavaScript is injected into a website. When a user visits the affected web page, the Javascript executes within that user’s br
The final sentence for this feels like a runoff, may be worth removing and making it

> **Cross-Site Scripting (XSS) is a type of injection attack where malicious JavaScript is injected into a website. When a user visits the affected web page, the Javascript executes within that user’s browser in the context of the domain.**

2022-05-12 06:25 UTC, evildaemond approved these changes
LGTM

2022-05-12 06:25 UTC, merged