XSS Off Domain via Data URI
bugcrowd/templates pull request #139
Opened 2022-05-11 03:44 UTC by RRudder

2022-05-11 06:55 UTC, evildaemond requested changes
1 change needs to be made

2022-05-11 06:55 UTC, evildaemond commented on submissions/description/cross_site_scripting_xss/off_domain/data_uri/template.md
> +Cross-Site Scripting (XSS) is a type of injection attack where malicious JavaScript is injected into a website. When a user visits the affected web page, the Javascript executes within that user’s br
This feels very wordy, splitting this into 2 paragraphs will improve readability a whole lot

2022-05-11 09:59 UTC, RRudder commented on submissions/description/cross_site_scripting_xss/off_domain/data_uri/template.md
> +Cross-Site Scripting (XSS) is a type of injection attack where malicious JavaScript is injected into a website. When a user visits the affected web page, the Javascript executes within that user’s br
Good pick up, thanks

2022-05-12 06:28 UTC, evildaemond approved these changes
LGTM

2022-05-12 06:29 UTC, merged