XSS Off Domain updates
bugcrowd/templates pull request #140
Opened 2022-05-11 10:31 UTC by RRudder

2022-05-12 06:39 UTC, evildaemond requested changes
1 Direct change

2022-05-12 06:39 UTC, evildaemond commented on submissions/description/cross_site_scripting_xss/off_domain/template.md
> +This carries the risk of an attacker being able to trigger an exploit on a separate domain. By controlling code that is executed within a user’s browser, an attacker could carry out any actions that
I think there should be some clarification here regarding the impact, triggering on a seperate domain usually means cookies won't be scoped for that domain, and you won't be able to use the users cookies, and makes the impact much more negligible. I've included a sample below

> This carries the risk of an attacker being able to trigger an exploit on a separate domain, which only means cookies scoped for that domain are at risk. By controlling code that is executed within a user’s browser, an attacker could carry out actions that the user is able to perform, this could include accessing any of the user's data and modifying information within the user’s permissions, assuming there is a misconfiguration of the scoping for cookies and CORS.

2022-05-12 10:06 UTC, RRudder commented on submissions/description/cross_site_scripting_xss/off_domain/template.md
> +This carries the risk of an attacker being able to trigger an exploit on a separate domain. By controlling code that is executed within a user’s browser, an attacker could carry out any actions that
TY mate

2022-05-17 06:56 UTC, evildaemond approved these changes
LGTM

2022-05-17 06:56 UTC, merged