Create template.md
bugcrowd/templates pull request #399
Opened 2022-09-12 15:40 UTC by tess-ss

2023-10-17 06:39 UTC, RRudder commented
Nice write up.

This template covers the adding LDAP Injection to the VRT (VRT PR [#367](https://github.com/bugcrowd/vulnerability-rating-taxonomy/pull/367))

2023-10-31 06:11 UTC, evildaemond requested changes
Needs work before this could be accepted, recommend reviewing the notes provided.

2023-10-31 06:11 UTC, evildaemond commented on submissions/description/server_side_injection/ldap_injection/template.md
> +1. Replace ID value with the following payload:
This can be converted to 2 steps

1. In the request to `URI` modify the token `XYZ` by appending a quote ``` and you'll see an error return
2. You can replace this with the payload below and you'll see a response indicating an injection occuring

2023-10-31 06:11 UTC, evildaemond commented on submissions/description/server_side_injection/ldap_injection/template.md
> +Attackers might use an LDAP injection to insert malicious code that allows them to see all the usernames and passwords assigned to a system or to add their names as system administrators. A successfu
Business impact is about specific and measurable impact to the organisation as a whole, so going extremely specific on what an attacker could do is not required, and a general recommendation is this is a less technical area.

Some language here as well could be improved, but I'll try and avoid specifics, this is a drop in replacement (heavily based upon the [SQL injection template](https://github.com/bugcrowd/templates/blob/master/submissions/description/server_side_injection/sql_injection/template.md))

```text
LDAP injection could allow an attacker the ability to read or manipulate the data within the application, which could lead to reputational damage or regulatory fines. This could also result in reputational damage for the business through the impact to customers’ trust. The severity of the impact to the business is dependent on the sensitivity of the data being stored in, and transmitted by the application.
```

2023-11-09 05:45 UTC, evildaemond approved these changes
LGTM

2023-11-09 05:45 UTC, merged