Update recommendation.md for SSRF DNS Query Only
bugcrowd/templates pull request #425
Opened 2023-04-28 03:40 UTC by RRudder

2024-05-15 03:07 UTC, norsec0de requested changes

2024-05-15 03:07 UTC, norsec0de commented on submissions/description/broken_access_control/server_side_request_forgery_ssrf/dns_query_only/recommendations.md
> +- Within the application layer, use an allow list for approved DNS servers that the application can query. Additionally, rate limit the number of DNS queries that can be requested  within a certain p
double space at "requested  within"

2024-05-15 22:35 UTC, norsec0de approved these changes

2024-06-19 00:35 UTC, RRudder commented
I'm going to delete this PR and the changes on this branch as they are outdated. 
SSRF now sits under Server Security Misconfiguration instead of Broken Access Control. Therefore, the changes on this branch are outdated.

2024-06-19 00:35 UTC, closed without merging