update rec for token leakage via referer trusted 3rd party
bugcrowd/templates pull request #471
Opened 2023-05-19 01:21 UTC by RRudder

2023-09-14 01:42 UTC, EvermoreBugcrowd requested changes

2023-09-14 01:42 UTC, EvermoreBugcrowd commented on submissions/description/sensitive_data_exposure/token_leakage_via_referer/trusted_third_party/template.md
> +Here is a list of the untrusted 3rd party hosts that leak the token:
"Here is a list of the untrusted 3rd party hosts that receive the token:"

Would be better wording, since they are receiving the leak, not doing the leaking.

2023-09-14 01:44 UTC, RRudder commented on submissions/description/sensitive_data_exposure/token_leakage_via_referer/trusted_third_party/template.md
> +Here is a list of the untrusted 3rd party hosts that leak the token:
Good pick up, TYVM

2024-05-15 02:33 UTC, norsec0de approved these changes

2024-05-15 02:58 UTC, merged