Update Steps to Repro for GET based open redirects
bugcrowd/templates pull request #483
Opened 2023-07-31 03:34 UTC by RRudder

2023-07-31 04:42 UTC, EvermoreBugcrowd requested changes
Step 1 wording still needs some work.

2023-07-31 04:42 UTC, EvermoreBugcrowd commented on submissions/description/unvalidated_redirects_and_forwards/open_redirect/get_based/template.md
> +1. Using a browser, navigate to the open redirect on the endpoint: {{URL_with_no_redirect}}
Oh, perhaps better wording here is "navigate to the vulnerable endpoint:"

'the open redirect on the endpoint:' is strange wording here considering that it does not include the redirect code at this point.

2023-07-31 04:54 UTC, EvermoreBugcrowd approved these changes
Awesome, looks good to me now.

2023-08-04 02:27 UTC, emma-ferguson approved these changes
LGTM

2023-11-22 23:31 UTC, RRudder commented
@ticidesign See if you can approve this

2023-11-22 23:32 UTC, ticidesign approved these changes
LGTM

2023-11-23 03:16 UTC, ticidesign approved these changes
LGTM

2024-04-18 02:48 UTC, ticidesign approved these changes
LGTM

2024-04-18 10:15 UTC, RRudder commented
@evildaemond could you please approve this PR? Ta!

2024-05-15 02:00 UTC, norsec0de approved these changes
Looks good to me

2024-05-15 02:47 UTC, merged