updates to Failure to Invalid Session on Password Change finding
bugcrowd/templates pull request #76
Opened 2022-02-25 06:28 UTC by RRudder

* Added info into template.md
* Added a recommendations.md
* Moved guidance to guidance.md

2022-03-01 03:05 UTC, arcwhite requested changes

2022-03-01 03:05 UTC, arcwhite commented on submissions/description/broken_authentication_and_session_management/failure_to_invalidate_session/on_password_change/guidance.md
> +Provide a 1-2 sentence description - see [CVE Project's Key Details Phrasing Guide](http://cveproject.github.io/docs/content/key-details-phrasing.pdf) for tips. Provide a step-by-step walkthrough on
I was kinda surprised at how much of this text would actually fit as a hint next to the description field, but it almost does, depending on where the hint text begins. It's pretty big though - can we reduce this at all?

2022-03-01 03:19 UTC, RRudder commented on submissions/description/broken_authentication_and_session_management/failure_to_invalidate_session/on_password_change/guidance.md
> +Provide a 1-2 sentence description - see [CVE Project's Key Details Phrasing Guide](http://cveproject.github.io/docs/content/key-details-phrasing.pdf) for tips. Provide a step-by-step walkthrough on
Yeah, the default guidance text is nice and short. I'll be more mindful of the length of it when I add in specific info.
I'll have a go now at reducing the size of this one :)

2022-04-06 01:44 UTC, RRudder commented
Hey Andy, please review the changes to the guidance text when you get a chance. Not urgent.

2022-04-12 05:53 UTC, arcwhite approved these changes
Noice!

2022-04-22 01:00 UTC, codingo approved these changes

2022-04-22 01:01 UTC, merged